default: &default
  adapter: postgresql
  port: 5432
  encoding: unicode
  pool: 5

development:
  <<: *default
  url: 'postgres://localhost/shopify_app_8_sequel_development'

test:
  <<: *default
  url: 'postgres://localhost/shopify_app_8_sequel_test'

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
